### ISSUE TITLE
Add refresh button to refresh the server

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/tiled-viz2023#48]

**Comment by prjemian** [comment]
Instead of adding a button to the GUI, trigger a refresh from the filter panel by  pressing `[Enter]` in any of the QLineEdit widgets.  Like this:

```py
        self.mainwindow.filter_panel.plan_name.returnPressed.connect(self.displayTable)
```

which could be added after this line: https://github.com/BCDA-APS/tiled-viz2023/blob/7285cc3731f0a89126082e2637d1dca2754d7212/gemviz23/demo/resultwindow.py#L186

**Comment by prjemian** [comment]
The `self.cat` object knows its own name:

```py
        print(f"Displaying catalog: {self.cat.item['id']!r}")
```

**Comment by olliviergassant** [comment]
Got this error message:


```py
(base) [wow ~/Documents/tiled-viz2023] /home/beams/OGASSANT/.conda/envs/bluesky_2023_2/bin/python /home/beams/OGASSANT/Documents/tiled-viz2023/gemviz23/demo/app.py
catalogSelected: args = ('developer',)  kwargs = {}
Displaying catalog: developer
doPageSize value ='5'
doPager action ='pageSize', value ='5'
self.pageOffset() =0 self.pageSize() =5
Traceback (most recent call last):
  File "/home/beams0/OGASSANT/Documents/tiled-viz2023/gemviz23/demo/resultwindow.py", line 240, in displayTable
    self.cat = server[args[0]]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/beams0/OGASSANT/Documents/tiled-viz2023/gemviz23/demo/resultwindow.py", line 240, in displayTable
    self.cat = server[args[0]]
IndexError: tuple index out of range
```

**Comment by prjemian** [comment]
Request renewed in #93.
