### ISSUE TITLE
BUG: error getting start time of first run from empty catalog

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-viz2023#68]
Browsing a catalog and got an error where there were no runs but at least one was expected:

```py
catalogSelected: args = ('30id-nrs30',)  kwargs = {}
Traceback (most recent call last):
  File "/home/beams/JEMIAN/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/tiled/iterviews.py", line 60, in __getitem__
    (key,) = keys
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beams1/JEMIAN/Documents/projects/BCDA-APS/gemviz23/gemviz23/demo/filterpanel.py", line 53, in catalogSelected
    getStartTime(cat.keys().first()),
  File "/home/beams/JEMIAN/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/tiled/iterviews.py", line 18, in first
    return self[0]
  File "/home/beams/JEMIAN/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/tiled/iterviews.py", line 62, in __getitem__
    raise IndexError("Index out of range")
IndexError: Index out of range
```

The application quit completely.

**Comment by prjemian** [comment]
Need to verify that `len(cat) > 0`.  Disable the slider if there are no runs.  Enable the slider if there _are_ runs.

**Comment by prjemian** [comment]
See #77
